---
- hosts: jenkins-master
  become: true
  tasks:
  - name: add apt key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present

  - name: add jenkins apt repository
    apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present


  - name: install java
    apt:
      name: openjdk-11-jre
      state: present
      update_cache: yes


  - name: install jenkins
    apt:
      name: jenkins
      state: present
      update_cache: yes


  - name: start jenkins service
    service:
      name: jenkins
      state: started
      enabled: true

  - name: start service at rboot
    systemd:
      name: jenkins
      state: started
      enabled: true

